name: Build

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            base-devel
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-vapoursynth
            mingw-w64-ucrt-x86_64-meson
            mingw-w64-ucrt-x86_64-ninja
      - name: Build
        run: |
          meson setup -Dstatic=true build
          meson compile -C build
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: IVTCDN-plugin-windows
          path: |
            build/ivtcdn.dll